### PR TITLE
Remove cookie dropping

### PR DESCRIPTION
**Pull request by ostapneko**
- Remove the cookie dropping from the "adfree" endpoint
- Rename the "adfree" endpoint to "features"
- Have the "features" endpoint return only a JSON response containing the identity id, an `adFree` flag and a, `adblockMessage` flag
- Have the "membership" endpoint also return the identity id

@jbreckmckye Are you OK with the naming?
@rtyley  Sorry for the unfortunate renaming...

### CODE REVIEW

**Comment by rtyley** [comment]
@ostapneko  Can you add a sample JSON response to the description?

**Comment by jbreckmckye** [comment]
@ostapneko - The naming seems absolutely fine to me :+1:

**Comment by ostapneko** [comment]
@rtyley This is on the Readme: https://github.com/guardian/membership-attribute-service/commit/1aca06b0579b4507ac438101f2772a9d7a7c64c3#diff-04c6e90faac2675aa89e2176d2eec7d8R16

**Comment by rtyley** [comment]
:+1:

**Comment by ostapneko** [comment]
image

image

**Pull request merged**
